source 'http://rubygems.org'

gem "rails", "3.0.9"
gem "mysql2", "~> 0.2.7"
gem "rake"

gem "aws-s3"
gem "devise"
gem "ckeditor", "3.4.0"
gem "exception_notification", :git => "https://github.com/smartinez87/exception_notification.git"
gem "fog"
gem "haml"
gem "htmlentities"
gem "httparty"
gem "nested_form"
gem "paperclip"
gem "postmark-rails"
gem "rack-ssl"
gem "sass"
gem "soap4r"
gem "will_paginate", "3.0.pre2"
